// REGISTER:
POST http://localhost:3000/api/auth/register
content-type: application/json

{
  "email": "williamkasbar1@gmail.com",
  "password": "password123",
  "name": "Albert",
  "lastname": "Palacios"
}

###
// LOGIN:
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "email": "williamkasbar1@gmail.com",
  "password": "password123"
}

###
// LOGOUT:
POST http://localhost:3000/api/auth/logout

###
// PRODUCTS:
GET http://localhost:3000/api/products

###
// PRODUCT_ID:
GET http://localhost:3000/api/products/b5cd991f-4425-48de-acf1-6376916bcc61